Changed the configuration options for OpenGL. "--with-GL" and "--with-Mesa-GL" have been replaced by "--with-GL=auto/GL/MesaGL/no". It is now possible to specify that GtkAda should be compiled without OpenGL, even if configure found it.
Autoconf rerun

diff --git a/contrib/configure b/contrib/configure
--- a/contrib/configure
+++ b/contrib/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# From configure.in Revision: 1.13 
+# From configure.in Revision: 1.14 
 #############################################################
 #
 #  Adding some OS specific flags to the compiler
@@ -95,11 +95,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --disable-gtktest       Do not try to compile and run a test GTK program"
 ac_help="$ac_help
+  --with-GL=value         Which OpenGL library to compile GtkAda with (auto,GL,MesaGL,no)"
+ac_help="$ac_help
   --with-GL-prefix=DIR    Prefix where GL/MesaGL is installed"
-ac_help="$ac_help
-  --with-lib-GL           use '-lGL'"
-ac_help="$ac_help
-  --with-lib-MesaGL       use '-lMesaGL'"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -661,7 +659,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:665: checking host system type" >&5
+echo "configure:663: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -682,7 +680,7 @@ host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$host" 1>&6
 
 echo $ac_n "checking target system type""... $ac_c" 1>&6
-echo "configure:686: checking target system type" >&5
+echo "configure:684: checking target system type" >&5
 
 target_alias=$target
 case "$target_alias" in
@@ -700,7 +698,7 @@ target_os=`echo $target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$target" 1>&6
 
 echo $ac_n "checking build system type""... $ac_c" 1>&6
-echo "configure:704: checking build system type" >&5
+echo "configure:702: checking build system type" >&5
 
 build_alias=$build
 case "$build_alias" in
@@ -742,7 +740,7 @@ test "$host_alias" != "$target_alias" &&
    # Extract the first word of "diff", so it can be a program name with args.
 set dummy diff; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:746: checking for $ac_word" >&5
+echo "configure:744: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_DIFF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -796,7 +794,7 @@ This is the second line
 EOF
 
       echo $ac_n "checking for the correct diff option""... $ac_c" 1>&6
-echo "configure:800: checking for the correct diff option" >&5
+echo "configure:798: checking for the correct diff option" >&5
 
       if $DIFF -u $file_to_patch $file_to_patch > /dev/null 2>&1 ; then
          echo "$ac_t""-u" 1>&6
@@ -826,7 +824,7 @@ echo "configure:800: checking for the correct diff option" >&5
       # Extract the first word of "patch", so it can be a program name with args.
 set dummy patch; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:830: checking for $ac_word" >&5
+echo "configure:828: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PATCH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -867,7 +865,7 @@ fi
       else
 
 	 echo $ac_n "checking for the correct patch option""... $ac_c" 1>&6
-echo "configure:871: checking for the correct patch option" >&5
+echo "configure:869: checking for the correct patch option" >&5
 
 	 cat > $patch_file <<EOF
 --- $file_to_patch.ori Mon Mar  1 21:21:34 1999
@@ -910,7 +908,7 @@ EOF
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:914: checking for $ac_word" >&5
+echo "configure:912: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -939,7 +937,7 @@ if test -z "$CC"; then
   # Extract the first word of "cc", so it can be a program name with args.
 set dummy cc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:943: checking for $ac_word" >&5
+echo "configure:941: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -987,7 +985,7 @@ fi
 fi
 
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:991: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+echo "configure:989: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
 
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -997,11 +995,11 @@ ac_link='${CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 
 cross_compiling=$ac_cv_prog_cc_cross
 
 cat > conftest.$ac_ext <<EOF
-#line 1001 "configure"
+#line 999 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
-if { (eval echo configure:1005: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1003: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   ac_cv_prog_cc_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -1021,12 +1019,12 @@ if test $ac_cv_prog_cc_works = no; then
   { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:1025: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "configure:1023: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
-echo "configure:1030: checking whether we are using GNU C" >&5
+echo "configure:1028: checking whether we are using GNU C" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1035,7 +1033,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1039: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1037: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gcc=yes
 else
   ac_cv_prog_gcc=no
@@ -1050,7 +1048,7 @@ if test $ac_cv_prog_gcc = yes; then
   ac_save_CFLAGS="$CFLAGS"
   CFLAGS=
   echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
-echo "configure:1054: checking whether ${CC-cc} accepts -g" >&5
+echo "configure:1052: checking whether ${CC-cc} accepts -g" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1081,7 +1079,7 @@ fi
    # Extract the first word of "gnatmake", so it can be a program name with args.
 set dummy gnatmake; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1085: checking for $ac_word" >&5
+echo "configure:1083: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GNATMAKE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1116,7 +1114,7 @@ fi
    fi
 
    echo $ac_n "checking that your gnat compiler works with a simple example""... $ac_c" 1>&6
-echo "configure:1120: checking that your gnat compiler works with a simple example" >&5
+echo "configure:1118: checking that your gnat compiler works with a simple example" >&5
 
    rm -f conftest.adb
    cat << EOF > conftest.adb
@@ -1153,7 +1151,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1157: checking for $ac_word" >&5
+echo "configure:1155: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1190,7 +1188,7 @@ done
 
 
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:1194: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:1192: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1227,7 +1225,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:1231: checking for a BSD compatible install" >&5
+echo "configure:1229: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1279,7 +1277,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1283: checking for $ac_word" >&5
+echo "configure:1281: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_RANLIB'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1348,7 +1346,7 @@ fi
   # Extract the first word of "gtk-config", so it can be a program name with args.
 set dummy gtk-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1352: checking for $ac_word" >&5
+echo "configure:1350: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GTK_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1379,7 +1377,7 @@ fi
 
   min_gtk_version=1.2.2
   echo $ac_n "checking for GTK - version >= $min_gtk_version""... $ac_c" 1>&6
-echo "configure:1383: checking for GTK - version >= $min_gtk_version" >&5
+echo "configure:1381: checking for GTK - version >= $min_gtk_version" >&5
   no_gtk=""
   if test "$GTK_CONFIG" = "no" ; then
     no_gtk=yes
@@ -1403,7 +1401,7 @@ echo "configure:1383: checking for GTK - version >= $min_gtk_version" >&5
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat > conftest.$ac_ext <<EOF
-#line 1407 "configure"
+#line 1405 "configure"
 #include "confdefs.h"
 
 #include <gtk/gtk.h>
@@ -1469,7 +1467,7 @@ main ()
 }
 
 EOF
-if { (eval echo configure:1473: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1471: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -1503,7 +1501,7 @@ fi
           CFLAGS="$CFLAGS $GTK_CFLAGS"
           LIBS="$LIBS $GTK_LIBS"
           cat > conftest.$ac_ext <<EOF
-#line 1507 "configure"
+#line 1505 "configure"
 #include "confdefs.h"
 
 #include <gtk/gtk.h>
@@ -1513,7 +1511,7 @@ int main() {
  return ((gtk_major_version) || (gtk_minor_version) || (gtk_micro_version)); 
 ; return 0; }
 EOF
-if { (eval echo configure:1517: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1515: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
    echo "*** The test program compiled, but did not run. This usually means"
           echo "*** that the run-time linker is not finding GTK or finding the wrong"
@@ -1555,48 +1553,45 @@ rm -f conftest*
 
 # try to find OpenGL if present
    
-   # checking for openGL libraries
+
+   # checking for OpenGL libraries
+   # Check whether --with-GL or --without-GL was given.
+if test "${with_GL+set}" = set; then
+  withval="$with_GL"
+  :
+fi
+
    # Check whether --with-GL-prefix or --without-GL-prefix was given.
 if test "${with_GL_prefix+set}" = set; then
   withval="$with_GL_prefix"
   :
 fi
 
-   # Check whether --with-lib-GL or --without-lib-GL was given.
-if test "${with_lib_GL+set}" = set; then
-  withval="$with_lib_GL"
-  :
-fi
-
-   # Check whether --with-lib-MesaGL or --without-lib-MesaGL was given.
-if test "${with_lib_MesaGL+set}" = set; then
-  withval="$with_lib_MesaGL"
-  :
-fi
-
    
+
    if test "x$with_GL_prefix" = "x" ; then
-    GL_LDOPTS=""
-    GL_CFLAGS=""
+      GL_LDOPTS=""
+      GL_CFLAGS=""
    else
-    GL_LDOPTS="-L$with_GL_prefix/lib"
-    GL_CFLAGS="-I$with_GL_prefix/include"
+      GL_LDOPTS="-L$with_GL_prefix/lib"
+      GL_CFLAGS="-I$with_GL_prefix/include"
    fi
    
+
    saved_LIBS="$LIBS"
-   
-   echo $ac_n "checking OpenGL""... $ac_c" 1>&6
-echo "configure:1590: checking OpenGL" >&5
+ 
+   echo $ac_n "checking for OpenGL""... $ac_c" 1>&6
+echo "configure:1585: checking for OpenGL" >&5
    LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lGL"
    cat > conftest.$ac_ext <<EOF
-#line 1593 "configure"
+#line 1588 "configure"
 #include "confdefs.h"
 
 int main() {
  char glBegin(); glBegin(); 
 ; return 0; }
 EOF
-if { (eval echo configure:1600: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1595: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   have_GL=yes
 else
@@ -1608,18 +1603,18 @@ fi
 rm -f conftest*
    echo "$ac_t""$have_GL" 1>&6
    
-   echo $ac_n "checking Mesa""... $ac_c" 1>&6
-echo "configure:1613: checking Mesa" >&5
+   echo $ac_n "checking for Mesa""... $ac_c" 1>&6
+echo "configure:1608: checking for Mesa" >&5
    LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL"
    cat > conftest.$ac_ext <<EOF
-#line 1616 "configure"
+#line 1611 "configure"
 #include "confdefs.h"
 
 int main() {
  char glBegin(); glBegin(); 
 ; return 0; }
 EOF
-if { (eval echo configure:1623: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1618: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   have_MesaGL=yes
 else
@@ -1630,72 +1625,52 @@ else
 fi
 rm -f conftest*
    echo "$ac_t""$have_MesaGL" 1>&6
-   
-   if test "x$have_MesaGL" = "xno"; then
-    echo $ac_n "checking Mesa with pthreads""... $ac_c" 1>&6
-echo "configure:1637: checking Mesa with pthreads" >&5
-    LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL -lpthread"
-    cat > conftest.$ac_ext <<EOF
-#line 1640 "configure"
-#include "confdefs.h"
-
-int main() {
- char glBegin(); glBegin(); 
-; return 0; }
-EOF
-if { (eval echo configure:1647: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
-  rm -rf conftest*
-  have_MesaGL_pthread=yes
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  have_MesaGL_pthread=no
-fi
-rm -f conftest*
-    echo "$ac_t""$have_MesaGL_pthread" 1>&6
-   fi
-   
+    
    LIBS="$saved_LIBS"
    HAVE_OPENGL="False"
-   
-   if test "x$with_lib_GL" = "xyes"; then
-   
-     if test "x$have_GL" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lGLU -lGL"
-       HAVE_OPENGL="True"
-     else
-       { echo "configure: error: Missing GL library" 1>&2; exit 1; }
-     fi
-   
-   elif test "x$with_lib_MesaGL" = "xyes"; then
-   
-     if test "x$have_MesaGL" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
-       HAVE_OPENGL="True"
-     elif test "x$have_MesaGL_pthread" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
-       HAVE_OPENGL="True"
-     else
-       { echo "configure: error: Missing MesaGL library" 1>&2; exit 1; }
-     fi
-   
-   else
-   
-     if test "x$have_GL" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lGLU -lGL"
-       HAVE_OPENGL="True"
-     elif test "x$have_MesaGL" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
-       HAVE_OPENGL="True"
-     elif test "x$have_MesaGL_pthread" = "xyes"; then
-       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
-       HAVE_OPENGL="True"
-     else
-       echo "$ac_t""*** OpenGL support will not be integrated into GtkAda ***" 1>&6
-     fi
+
+ 
+   case "x$with_GL" in
+   x|xauto)
+      if test "x$have_GL" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+         HAVE_OPENGL="True"
+      elif test "x$have_MesaGL" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
+         HAVE_OPENGL="True"
+      elif test "x$have_MesaGL_pthread" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
+         HAVE_OPENGL="True"
+      fi
+      ;;
+   xGL)
+      if test "x$have_GL" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+         HAVE_OPENGL="True"
+      else
+         { echo "configure: error: Missing GL library" 1>&2; exit 1; }
+      fi
+      ;;
+   xMesaGL)
+      if test "x$have_MesaGL" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+         HAVE_OPENGL="True"
+      else
+         { echo "configure: error: Missing GL library" 1>&2; exit 1; }
+      fi
+      ;;
+   xno)
+      ;;
+   *)
+      { echo "configure: error: Unknown value for "--with-GL" option. Should be either auto, GL, MesaGL, no" 1>&2; exit 1; }
+      ;;
+   esac
+
+   if test "x$HAVE_OPENGL"="xFalse"; then
+      echo "$ac_t""*** OpenGL support will not be integrated into GtkAda ***" 1>&6
    fi
-   
+
+
    
    
    
