Reran autoconf after having changed aclocal.m4 and configure.in

diff --git a/contrib/configure b/contrib/configure
--- a/contrib/configure
+++ b/contrib/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# From configure.in Revision: 1.11 
+# From configure.in Revision: 1.13 
 #############################################################
 #
 #  Adding some OS specific flags to the compiler
@@ -45,6 +45,16 @@ conftest_ok="conftest.ok"
 file_to_patch="conftest"
 patch_file="conftest.dif"
 result_file="conftest.res"
+
+
+
+
+#############################################################
+#
+#  Checking for diff and patch
+#
+#############################################################
+
 
 
 # Guess values for system-dependent variables and create Makefiles.
@@ -631,7 +641,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:635: checking host system type" >&5
+echo "configure:645: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -652,7 +662,7 @@ host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$host" 1>&6
 
 echo $ac_n "checking target system type""... $ac_c" 1>&6
-echo "configure:656: checking target system type" >&5
+echo "configure:666: checking target system type" >&5
 
 target_alias=$target
 case "$target_alias" in
@@ -670,7 +680,7 @@ target_os=`echo $target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$target" 1>&6
 
 echo $ac_n "checking build system type""... $ac_c" 1>&6
-echo "configure:674: checking build system type" >&5
+echo "configure:684: checking build system type" >&5
 
 build_alias=$build
 case "$build_alias" in
@@ -712,7 +722,7 @@ test "$host_alias" != "$target_alias" &&
    # Extract the first word of "diff", so it can be a program name with args.
 set dummy diff; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:716: checking for $ac_word" >&5
+echo "configure:726: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_DIFF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -766,7 +776,7 @@ This is the second line
 EOF
 
       echo $ac_n "checking for the correct diff option""... $ac_c" 1>&6
-echo "configure:770: checking for the correct diff option" >&5
+echo "configure:780: checking for the correct diff option" >&5
 
       if $DIFF -u $file_to_patch $file_to_patch > /dev/null 2>&1 ; then
          echo "$ac_t""-u" 1>&6
@@ -796,7 +806,7 @@ echo "configure:770: checking for the correct diff option" >&5
       # Extract the first word of "patch", so it can be a program name with args.
 set dummy patch; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:800: checking for $ac_word" >&5
+echo "configure:810: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PATCH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -837,7 +847,7 @@ fi
       else
 
 	 echo $ac_n "checking for the correct patch option""... $ac_c" 1>&6
-echo "configure:841: checking for the correct patch option" >&5
+echo "configure:851: checking for the correct patch option" >&5
 
 	 cat > $patch_file <<EOF
 --- $file_to_patch.ori Mon Mar  1 21:21:34 1999
@@ -880,7 +890,7 @@ EOF
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:884: checking for $ac_word" >&5
+echo "configure:894: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -909,7 +919,7 @@ if test -z "$CC"; then
   # Extract the first word of "cc", so it can be a program name with args.
 set dummy cc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:913: checking for $ac_word" >&5
+echo "configure:923: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -957,7 +967,7 @@ fi
 fi
 
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:961: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+echo "configure:971: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
 
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -967,11 +977,11 @@ ac_link='${CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 
 cross_compiling=$ac_cv_prog_cc_cross
 
 cat > conftest.$ac_ext <<EOF
-#line 971 "configure"
+#line 981 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
-if { (eval echo configure:975: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:985: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   ac_cv_prog_cc_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -991,12 +1001,12 @@ if test $ac_cv_prog_cc_works = no; then
   { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:995: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "configure:1005: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
-echo "configure:1000: checking whether we are using GNU C" >&5
+echo "configure:1010: checking whether we are using GNU C" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1005,7 +1015,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1009: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:1019: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gcc=yes
 else
   ac_cv_prog_gcc=no
@@ -1020,7 +1030,7 @@ if test $ac_cv_prog_gcc = yes; then
   ac_save_CFLAGS="$CFLAGS"
   CFLAGS=
   echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
-echo "configure:1024: checking whether ${CC-cc} accepts -g" >&5
+echo "configure:1034: checking whether ${CC-cc} accepts -g" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1051,7 +1061,7 @@ fi
    # Extract the first word of "gnatmake", so it can be a program name with args.
 set dummy gnatmake; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1055: checking for $ac_word" >&5
+echo "configure:1065: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GNATMAKE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1086,7 +1096,7 @@ fi
    fi
 
    echo $ac_n "checking that your gnat compiler works with a simple example""... $ac_c" 1>&6
-echo "configure:1090: checking that your gnat compiler works with a simple example" >&5
+echo "configure:1100: checking that your gnat compiler works with a simple example" >&5
 
    rm -f conftest.adb
    cat << EOF > conftest.adb
@@ -1123,7 +1133,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1127: checking for $ac_word" >&5
+echo "configure:1137: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1160,7 +1170,7 @@ done
 
 
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:1164: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:1174: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1197,7 +1207,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:1201: checking for a BSD compatible install" >&5
+echo "configure:1211: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1249,7 +1259,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1253: checking for $ac_word" >&5
+echo "configure:1263: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_RANLIB'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1318,7 +1328,7 @@ fi
   # Extract the first word of "gtk-config", so it can be a program name with args.
 set dummy gtk-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1322: checking for $ac_word" >&5
+echo "configure:1332: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GTK_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1349,7 +1359,7 @@ fi
 
   min_gtk_version=1.2.0
   echo $ac_n "checking for GTK - version >= $min_gtk_version""... $ac_c" 1>&6
-echo "configure:1353: checking for GTK - version >= $min_gtk_version" >&5
+echo "configure:1363: checking for GTK - version >= $min_gtk_version" >&5
   no_gtk=""
   if test "$GTK_CONFIG" = "no" ; then
     no_gtk=yes
@@ -1373,7 +1383,7 @@ echo "configure:1353: checking for GTK - version >= $min_gtk_version" >&5
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat > conftest.$ac_ext <<EOF
-#line 1377 "configure"
+#line 1387 "configure"
 #include "confdefs.h"
 
 #include <gtk/gtk.h>
@@ -1439,7 +1449,7 @@ main ()
 }
 
 EOF
-if { (eval echo configure:1443: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1453: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -1473,7 +1483,7 @@ fi
           CFLAGS="$CFLAGS $GTK_CFLAGS"
           LIBS="$LIBS $GTK_LIBS"
           cat > conftest.$ac_ext <<EOF
-#line 1477 "configure"
+#line 1487 "configure"
 #include "confdefs.h"
 
 #include <gtk/gtk.h>
@@ -1483,7 +1493,7 @@ int main() {
  return ((gtk_major_version) || (gtk_minor_version) || (gtk_micro_version)); 
 ; return 0; }
 EOF
-if { (eval echo configure:1487: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1497: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
    echo "*** The test program compiled, but did not run. This usually means"
           echo "*** that the run-time linker is not finding GTK or finding the wrong"
@@ -1523,48 +1533,50 @@ rm -f conftest*
   rm -f conf.gtktest
 
 
-# checking for openGL libraries
-# Check whether --with-GL-prefix or --without-GL-prefix was given.
+# try to find OpenGL if present
+   
+   # checking for openGL libraries
+   # Check whether --with-GL-prefix or --without-GL-prefix was given.
 if test "${with_GL_prefix+set}" = set; then
   withval="$with_GL_prefix"
   :
 fi
 
-# Check whether --with-lib-GL or --without-lib-GL was given.
+   # Check whether --with-lib-GL or --without-lib-GL was given.
 if test "${with_lib_GL+set}" = set; then
   withval="$with_lib_GL"
   :
 fi
 
-# Check whether --with-lib-MesaGL or --without-lib-MesaGL was given.
+   # Check whether --with-lib-MesaGL or --without-lib-MesaGL was given.
 if test "${with_lib_MesaGL+set}" = set; then
   withval="$with_lib_MesaGL"
   :
 fi
 
-
-if test "x$with_GL_prefix" = "x" ; then
- GL_LDOPTS=""
- GL_CFLAGS=""
-else
- GL_LDOPTS="-L$with_GL_prefix/lib"
- GL_CFLAGS="-I$with_GL_prefix/include"
-fi
-
-saved_LIBS="$LIBS"
-
-echo $ac_n "checking OpenGL""... $ac_c" 1>&6
-echo "configure:1558: checking OpenGL" >&5
-LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lGL"
-cat > conftest.$ac_ext <<EOF
-#line 1561 "configure"
+   
+   if test "x$with_GL_prefix" = "x" ; then
+    GL_LDOPTS=""
+    GL_CFLAGS=""
+   else
+    GL_LDOPTS="-L$with_GL_prefix/lib"
+    GL_CFLAGS="-I$with_GL_prefix/include"
+   fi
+   
+   saved_LIBS="$LIBS"
+   
+   echo $ac_n "checking OpenGL""... $ac_c" 1>&6
+echo "configure:1570: checking OpenGL" >&5
+   LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lGL"
+   cat > conftest.$ac_ext <<EOF
+#line 1573 "configure"
 #include "confdefs.h"
 
 int main() {
  char glBegin(); glBegin(); 
 ; return 0; }
 EOF
-if { (eval echo configure:1568: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1580: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   have_GL=yes
 else
@@ -1574,20 +1586,20 @@ else
   have_GL=no
 fi
 rm -f conftest*
-echo "$ac_t""$have_GL" 1>&6
-
-echo $ac_n "checking Mesa""... $ac_c" 1>&6
-echo "configure:1581: checking Mesa" >&5
-LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL"
-cat > conftest.$ac_ext <<EOF
-#line 1584 "configure"
+   echo "$ac_t""$have_GL" 1>&6
+   
+   echo $ac_n "checking Mesa""... $ac_c" 1>&6
+echo "configure:1593: checking Mesa" >&5
+   LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL"
+   cat > conftest.$ac_ext <<EOF
+#line 1596 "configure"
 #include "confdefs.h"
 
 int main() {
  char glBegin(); glBegin(); 
 ; return 0; }
 EOF
-if { (eval echo configure:1591: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1603: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   have_MesaGL=yes
 else
@@ -1597,21 +1609,21 @@ else
   have_MesaGL=no
 fi
 rm -f conftest*
-echo "$ac_t""$have_MesaGL" 1>&6
-
-if test "x$have_MesaGL" = "xno"; then
- echo $ac_n "checking Mesa with pthreads""... $ac_c" 1>&6
-echo "configure:1605: checking Mesa with pthreads" >&5
- LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL -lpthread"
- cat > conftest.$ac_ext <<EOF
-#line 1608 "configure"
+   echo "$ac_t""$have_MesaGL" 1>&6
+   
+   if test "x$have_MesaGL" = "xno"; then
+    echo $ac_n "checking Mesa with pthreads""... $ac_c" 1>&6
+echo "configure:1617: checking Mesa with pthreads" >&5
+    LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGL -lpthread"
+    cat > conftest.$ac_ext <<EOF
+#line 1620 "configure"
 #include "confdefs.h"
 
 int main() {
  char glBegin(); glBegin(); 
 ; return 0; }
 EOF
-if { (eval echo configure:1615: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1627: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   have_MesaGL_pthread=yes
 else
@@ -1621,50 +1633,52 @@ else
   have_MesaGL_pthread=no
 fi
 rm -f conftest*
- echo "$ac_t""$have_MesaGL_pthread" 1>&6
-fi
-
-LIBS="$saved_LIBS"
-HAVE_OPENGL=no_opengl
-
-if test "x$with_lib_GL" = "xyes"; then
-
-  if test "x$have_GL" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lGLU -lGL"
-    HAVE_OPENGL=opengl
-  else
-    { echo "configure: error: Missing GL library" 1>&2; exit 1; }
-  fi
-
-elif test "x$with_lib_MesaGL" = "xyes"; then
-
-  if test "x$have_MesaGL" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
-    HAVE_OPENGL=opengl
-  elif test "x$have_MesaGL_pthread" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
-    HAVE_OPENGL=opengl
-  else
-    { echo "configure: error: Missing MesaGL library" 1>&2; exit 1; }
-  fi
-
-else
-
-  if test "x$have_GL" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lGLU -lGL"
-    HAVE_OPENGL=opengl
-  elif test "x$have_MesaGL" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
-    HAVE_OPENGL=opengl
-  elif test "x$have_MesaGL_pthread" = "xyes"; then
-    GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
-    HAVE_OPENGL=opengl
-  else
-    echo "$ac_t""openGL support will not be integrated into GtkAda" 1>&6
-  fi
-fi
-
-
+    echo "$ac_t""$have_MesaGL_pthread" 1>&6
+   fi
+   
+   LIBS="$saved_LIBS"
+   HAVE_OPENGL=no_opengl
+   
+   if test "x$with_lib_GL" = "xyes"; then
+   
+     if test "x$have_GL" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+       HAVE_OPENGL=opengl
+     else
+       { echo "configure: error: Missing GL library" 1>&2; exit 1; }
+     fi
+   
+   elif test "x$with_lib_MesaGL" = "xyes"; then
+   
+     if test "x$have_MesaGL" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
+       HAVE_OPENGL=opengl
+     elif test "x$have_MesaGL_pthread" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
+       HAVE_OPENGL=opengl
+     else
+       { echo "configure: error: Missing MesaGL library" 1>&2; exit 1; }
+     fi
+   
+   else
+   
+     if test "x$have_GL" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lGLU -lGL"
+       HAVE_OPENGL=opengl
+     elif test "x$have_MesaGL" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
+       HAVE_OPENGL=opengl
+     elif test "x$have_MesaGL_pthread" = "xyes"; then
+       GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL -lpthread"
+       HAVE_OPENGL=opengl
+     else
+       echo "$ac_t""*** OpenGL support will not be integrated into GtkAda ***" 1>&6
+     fi
+   fi
+   
+   
+   
+   
 
 
 
