Include configure hunk, needed to build automatically glade. Should fix Gtk+ build failures.

diff --git a/contrib/glade-2.0.0.diff b/contrib/glade-2.0.0.diff
--- a/contrib/glade-2.0.0.diff
+++ b/contrib/glade-2.0.0.diff
@@ -73,6 +73,74 @@ Thu Jun 12 12:05:57 CEST 2003	Nicolas Setton	<setton@act-europe.fr>
  dnl Debugging - defines GLADE_DEBUG if --enable-debug option is used.
  dnl ***************************************************************************
  
+--- configure.old	Fri Apr 11 14:37:55 2003
++++ configure	Thu Jun 15 15:00:04 2006
+@@ -11925,56 +11925,6 @@ fi
+ 
+ 
+ 
+-# Extract the first word of "scrollkeeper-config", so it can be a program name with args.
+-set dummy scrollkeeper-config; ac_word=$2
+-echo "$as_me:$LINENO: checking for $ac_word" >&5
+-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+-if test "${ac_cv_path_SCROLLKEEPER_CONFIG+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  case $SCROLLKEEPER_CONFIG in
+-  [\\/]* | ?:[\\/]*)
+-  ac_cv_path_SCROLLKEEPER_CONFIG="$SCROLLKEEPER_CONFIG" # Let the user override the test with a path.
+-  ;;
+-  *)
+-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+-for as_dir in $PATH
+-do
+-  IFS=$as_save_IFS
+-  test -z "$as_dir" && as_dir=.
+-  for ac_exec_ext in '' $ac_executable_extensions; do
+-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+-    ac_cv_path_SCROLLKEEPER_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+-    break 2
+-  fi
+-done
+-done
+-
+-  test -z "$ac_cv_path_SCROLLKEEPER_CONFIG" && ac_cv_path_SCROLLKEEPER_CONFIG="no"
+-  ;;
+-esac
+-fi
+-SCROLLKEEPER_CONFIG=$ac_cv_path_SCROLLKEEPER_CONFIG
+-
+-if test -n "$SCROLLKEEPER_CONFIG"; then
+-  echo "$as_me:$LINENO: result: $SCROLLKEEPER_CONFIG" >&5
+-echo "${ECHO_T}$SCROLLKEEPER_CONFIG" >&6
+-else
+-  echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6
+-fi
+-
+-if test "$SCROLLKEEPER_CONFIG" = "no"; then
+-  { { echo "$as_me:$LINENO: error: Couldn't find scrollkeeper-config" >&5
+-echo "$as_me: error: Couldn't find scrollkeeper-config" >&2;}
+-   { (exit please install the scrollkeeper package); exit please install the scrollkeeper package; }; }
+-fi
+-SCROLLKEEPER_REQUIRED=0.1.4
+-
+-
+-
+-
+ # Check whether --enable-debug or --disable-debug was given.
+ if test "${enable_debug+set}" = set; then
+   enableval="$enable_debug"
+@@ -12668,8 +12618,6 @@ s,@INTLOBJS@,$INTLOBJS,;t t
+ s,@POFILES@,$POFILES,;t t
+ s,@POSUB@,$POSUB,;t t
+ s,@MKINSTALLDIRS@,$MKINSTALLDIRS,;t t
+-s,@SCROLLKEEPER_CONFIG@,$SCROLLKEEPER_CONFIG,;t t
+-s,@SCROLLKEEPER_REQUIRED@,$SCROLLKEEPER_REQUIRED,;t t
+ CEOF
+ 
+ _ACEOF
 --- glade/utils.c.old	2003-06-17 14:26:50.000000000 +0100
 +++ glade/utils.c	2003-06-17 14:26:57.000000000 +0100
 @@ -21,13 +21,8 @@
