Add detection of glut as a valid OpenGL driver under Windows. For J528-025.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -813,7 +813,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-GL=value         Which OpenGL library to compile GtkAda with (auto,GL,MesaGL,no)
+  --with-GL=value         Which OpenGL library to compile GtkAda with (auto,GL,glut,MesaGL,,no)
   --with-GL-prefix=DIR    Prefix where GL/MesaGL is installed
 
 Some influential environment variables:
@@ -3552,6 +3552,51 @@ rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
      echo "$as_me:$LINENO: result: $have_GL" >&5
 echo "${ECHO_T}$have_GL" >&6
 
+     echo "$as_me:$LINENO: checking for glut" >&5
+echo $ECHO_N "checking for glut... $ECHO_C" >&6
+     LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lglu32 -lglut32 -lopengl32 -lgdi32"
+     cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <GL/gl.h>
+#include <windows.h>
+int
+main ()
+{
+ glBegin(0);
+  CreateCompatibleDC(NULL);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_GL=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+have_GL=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+     echo "$as_me:$LINENO: result: $have_GL" >&5
+echo "${ECHO_T}$have_GL" >&6
+
      echo "$as_me:$LINENO: checking for Mesa" >&5
 echo $ECHO_N "checking for Mesa... $ECHO_C" >&6
      LIBS="$saved_LIBS $GTK_LIBS $GL_LDOPTS -lMesaGLU -lMesaGL"
@@ -3647,7 +3692,10 @@ echo "${ECHO_T}$have_MesaGL_pthread" >&6
       if test "x$have_GL" = "xyes"; then
          GL_LIBS="$GL_LDOPTS -lGLU -lGL"
          HAVE_OPENGL="True"
-      elif test "x$have_MesaGL" = "xyes"; then
+      elif test "x$have_glut" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lglu32 -lglut32 -lopengl32 -lgdi32"
+         HAVE_OPENGL="True"
+     elif test "x$have_MesaGL" = "xyes"; then
          GL_LIBS="$GL_LDOPTS -lMesaGLU -lMesaGL"
          HAVE_OPENGL="True"
       elif test "x$have_MesaGL_pthread" = "xyes"; then
@@ -3662,6 +3710,16 @@ echo "${ECHO_T}$have_MesaGL_pthread" >&6
       else
          { { echo "$as_me:$LINENO: error: Missing OpenGL library" >&5
 echo "$as_me: error: Missing OpenGL library" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+      ;;
+   xglut)
+      if test "x$have_GL" = "xyes"; then
+         GL_LIBS="$GL_LDOPTS -lglu32 -lglut32 -lopengl32 -lgdi32"
+         HAVE_OPENGL="True"
+      else
+         { { echo "$as_me:$LINENO: error: Missing glut library" >&5
+echo "$as_me: error: Missing glut library" >&2;}
    { (exit 1); exit 1; }; }
       fi
       ;;
@@ -3681,8 +3739,8 @@ echo "$as_me: error: Missing Mesa library" >&2;}
    xno)
       ;;
    *)
-      { { echo "$as_me:$LINENO: error: Unknown value for \"--with-GL\" option. Should be either auto, GL, MesaGL, no" >&5
-echo "$as_me: error: Unknown value for \"--with-GL\" option. Should be either auto, GL, MesaGL, no" >&2;}
+      { { echo "$as_me:$LINENO: error: Unknown value for \"--with-GL\" option. Should be either auto, glut, GL, MesaGL, no" >&5
+echo "$as_me: error: Unknown value for \"--with-GL\" option. Should be either auto, glut, GL, MesaGL, no" >&2;}
    { (exit 1); exit 1; }; }
       ;;
    esac
